# Generated by Django 4.2.7 on 2024-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('first_rows', models.TextField()),
                ('summary_stats', models.TextField()),
                ('missing_values', models.TextField()),
            ],
        ),
    ]
